mia_enabled_nodes = {
    {
        node_name = "default:gravel",
        tools = {
            "default:shovel_wood",
            "default:shovel_stone",
            "default:shovel_steel",
            "default:shovel_bronze",
            "default:shovel_mese",
            "default:shovel_diamond",
        },
    },
    {
        node_name = "default:clay",
        tools = {
            "default:shovel_wood",
            "default:shovel_stone",
            "default:shovel_steel",
            "default:shovel_bronze",
            "default:shovel_mese",
            "default:shovel_diamond",
        },
    },
    {
        node_name = "default:tree",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:wood",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:leaves",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:jungletree",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:junglewood",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:jungleleaves",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:pine_tree",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:pine_wood",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:pine_needles",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:acacia_tree",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:acacia_wood",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:acacia_leaves",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:aspen_tree",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:aspen_wood",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:aspen_leaves",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:papyrus",
        tools = {
            "default:axe_wood",
            "default:axe_stone",
            "default:axe_steel",
            "default:axe_bronze",
            "default:axe_mese",
            "default:axe_diamond",
        },
    },
    {
        node_name = "default:stonebrick",
        tools = {
            "default:pick_wood",
            "default:pick_stone",
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:desert_stonebrick",
        tools = {
            "default:pick_wood",
            "default:pick_stone",
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:sandstonebrick",
        tools = {
            "default:pick_wood",
            "default:pick_stone",
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:obsidian",
        tools = {
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:obsidianbrick",
        tools = {
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:stone_with_coal",
        tools = {
            "default:pick_wood",
            "default:pick_stone",
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:coalblock",
        tools = {
            "default:pick_wood",
            "default:pick_stone",
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:stone_with_iron",
        tools = {
            "default:pick_wood",
            "default:pick_stone",
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:steelblock",
        tools = {
            "default:pick_wood",
            "default:pick_stone",
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:stone_with_copper",
        tools = {
            "default:pick_wood",
            "default:pick_stone",
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:copperblock",
        tools = {
            "default:pick_stone",
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:bronzeblock",
        tools = {
            "default:pick_stone",
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:stone_with_gold",
        tools = {
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:goldblock",
        tools = {
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:stone_with_mese",
        tools = {
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:mese",
        tools = {
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:stone_with_diamond",
        tools = {
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
    {
        node_name = "default:diamondblock",
        tools = {
            "default:pick_steel",
            "default:pick_bronze",
            "default:pick_mese",
            "default:pick_diamond",
        },
    },
}
